# Generated by Django 3.0.8 on 2020-11-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_auto_20201104_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='ФИО'),
        ),
    ]
