# Generated by Django 3.0.8 on 2020-11-10 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0025_auto_20201109_0751'),
        ('hello', '0024_auto_20201109_0750'),
    ]

    operations = [
    ]
