# Generated by Django 3.0.8 on 2020-11-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0026_merge_20201110_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(max_length=50, null=True)),
                ('type_payment', models.CharField(blank=True, max_length=50, null=True)),
                ('valute_card', models.CharField(blank=True, max_length=10, null=True)),
                ('card_number', models.CharField(blank=True, max_length=30, null=True)),
                ('owner_card', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='card_number',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
    ]
