# Generated by Django 3.1.3 on 2020-11-10 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0026_merge_20201109_0326'),
        ('hello', '0027_auto_20201110_0846'),
    ]

    operations = [
    ]
