# Generated by Django 3.1.3 on 2020-11-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0028_merge_20201110_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='published',
            field=models.DateField(db_index=True, null=True, verbose_name='Дата заключение договора'),
        ),
    ]
