# Generated by Django 3.1.3 on 2020-11-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0029_auto_20201111_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='published',
            field=models.CharField(max_length=50, null=True, verbose_name='Дата заключение договора'),
        ),
    ]
