# Generated by Django 3.1.3 on 2020-11-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0030_auto_20201111_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_card',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Срок карты'),
        ),
    ]
