# Generated by Django 3.1.3 on 2020-11-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0031_auto_20201115_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_birthday',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_passport',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_passport',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_main_st',
            field=models.FileField(blank=True, upload_to='', verbose_name='Паспорт главная ст.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_st_registration',
            field=models.FileField(blank=True, upload_to='', verbose_name='Паспорт ст. регистрации'),
        ),
        migrations.AddField(
            model_name='profile',
            name='place_registration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место регистрации'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reward',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вознаграждение'),
        ),
        migrations.AddField(
            model_name='profile',
            name='signed_contract',
            field=models.FileField(blank=True, upload_to='', verbose_name='Подписанный договор'),
        ),
        migrations.AddField(
            model_name='profile',
            name='who_gave',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кем выдан'),
        ),
    ]
