# Generated by Django 3.1.3 on 2020-11-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0032_auto_20201119_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='acc_pre_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(max_length=40, null=True, verbose_name='Псевдоним')),
                ('month', models.CharField(max_length=100, null=True)),
                ('year', models.IntegerField(null=True, verbose_name='Год')),
                ('status', models.CharField(max_length=100, null=True)),
                ('day_payment', models.CharField(max_length=40, null=True, verbose_name='Дата оплата')),
                ('document', models.FileField(null=True, upload_to='%Y/%m/%d/')),
                ('summa', models.CharField(max_length=20, null=True)),
                ('card_number', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='prof_pre_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.CharField(max_length=50, null=True, verbose_name='Дата заключение договора')),
                ('login', models.CharField(max_length=50, null=True, verbose_name='Логин')),
                ('parol', models.CharField(max_length=50, null=True, verbose_name='Парол')),
                ('pseudonym', models.CharField(max_length=50, null=True, verbose_name='Псевдоним')),
                ('number', models.IntegerField(blank=True, verbose_name='')),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='t')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('prefix', models.CharField(max_length=20, null=True)),
                ('type_payment', models.CharField(max_length=50, null=True)),
                ('valute_card', models.CharField(max_length=10, null=True)),
                ('card_number', models.CharField(max_length=30, null=True)),
                ('date_card', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_card', models.CharField(max_length=100, null=True)),
                ('date_birthday', models.CharField(blank=True, max_length=30, null=True, verbose_name='Дата рождения')),
                ('number_passport', models.CharField(blank=True, max_length=20, null=True, verbose_name='Серия и номер паспорта')),
                ('date_passport', models.CharField(blank=True, max_length=30, null=True, verbose_name='Дата выдачи паспорта')),
                ('who_gave', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кем выдан')),
                ('place_registration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место регистрации')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('bank', models.CharField(blank=True, max_length=100, null=True, verbose_name='Банк')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вознаграждение')),
                ('passport_main_st', models.FileField(blank=True, upload_to='', verbose_name='Паспорт главная ст.')),
                ('passport_st_registration', models.FileField(blank=True, upload_to='', verbose_name='Паспорт ст. регистрации')),
                ('signed_contract', models.FileField(blank=True, upload_to='', verbose_name='Подписанный договор')),
            ],
        ),
        migrations.CreateModel(
            name='sendmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('admin', models.CharField(max_length=50, null=True)),
                ('select', models.CharField(max_length=50, null=True)),
                ('message', models.TextField(max_length=500, null=True)),
                ('user', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('admin', models.CharField(max_length=100, null=True)),
                ('obj', models.CharField(max_length=20, null=True)),
                ('text', models.TextField(null=True)),
                ('obj_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_birthday',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_passport',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Дата выдачи паспорта'),
        ),
    ]
