# Generated by Django 3.1.3 on 2020-11-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0033_auto_20201122_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof_pre_value',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=''),
        ),
    ]
