# Generated by Django 3.1.3 on 2020-11-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0035_auto_20201125_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof_pre_value',
            name='tg_phone_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tg_phone_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
