# Generated by Django 3.1.3 on 2020-11-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0036_auto_20201127_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
