# Generated by Django 3.1.3 on 2020-12-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0037_auto_20201128_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof_pre_value',
            name='card_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='prof_pre_value',
            name='owner_card',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prof_pre_value',
            name='type_payment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prof_pre_value',
            name='valute_card',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='card_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='owner_card',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Владелец карты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_payment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='valute_card',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта карты'),
        ),
    ]
