# Generated by Django 3.1.3 on 2021-01-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0040_auto_20201203_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='happybirthday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True, verbose_name='Текст для отправки')),
                ('hour', models.CharField(max_length=10, null=True, verbose_name='')),
                ('minute', models.CharField(max_length=10, null=True, verbose_name=':')),
            ],
        ),
    ]
