# Generated by Django 3.1.3 on 2021-04-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0043_audio_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
